#cloud-config
packages:
  - nginx

write_files:
  - path: /etc/nginx/conf.d/default.conf
    content: |
      server {
          listen 80;
          server_name _;
          location /jenkins/ {
              proxy_pass http://${jenkins_ip}:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_redirect off;
          }
          location /nextcloud/ {
              proxy_pass http://${nextcloud_ip}:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_redirect off;
          }
      }

runcmd:
  - systemctl restart nginx