  #cloud-config
package_update: true
package_upgrade: false

runcmd:
  - apt-get update
  - apt-get install -y gnupg2 wget apt-transport-https ca-certificates
  - apt-get install -y openjdk-17-jdk
  - sudo wget -O /etc/apt/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
  - echo "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc]" https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  - apt-get update
  - apt-get install -y jenkins
  - systemctl enable jenkins
  - systemctl start jenkins
