spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: 4413dd4f-5310-4d32-935f-265d9a21fd55
            client-secret: 
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/azure"
            client-name: Azure
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/d929fb20-8810-428f-896b-9e7ee0264990/v2.0
server:
  port: 8080
